---
- name: Configure MOTD
  hosts: all
  connection: network_cli
  gather_facts: no
  vars:
    ansible_network_os: cisco.ios.ios
    ansible_user: "{{ username }}"
    ansible_password: "{{ password }}"
  tasks:
    - name: Set MOTD Banner
      ios_config:
        lines:
          - banner motd !{{ motd_message }}!
