---
- name: Grab running-config
  hosts: all
  gather_facts: no
  connection: network_cli
  vars:
    ansible_network_os: cisco.ios.ios
    ansible_user: "{{ username }}"
    ansible_password: "{{ password }}"

  tasks:
    - name: Show running-config
      cisco.ios.ios_command:
        commands:
          - show running-config
      register: runout

    - name: Print running-config to stdout
      debug:
        var: runout.stdout[0]
